### ISSUE TITLE
Possible unfare comparison

### ISSUE THREAD

**Issue by piskov** [usefulsensors/qc_npu_benchmark#2]
Snapdragon touts 45 TOPS but it’s only int8.

For example Apple's m3 neural engine is mere 18 TOPS but it’s FP16.

So windows has bigger number but it’s not apple to apple comparison.

Question: do you test int8 performance?

**Comment by schmorp** [comment]
they clearly write about that, yes, they test using int8 with fp32 in/out and int8 with int8 in/out.
